"""Create a git-ignored .env with fresh local-development secrets. Never use these in deployment."""

from __future__ import annotations

import base64
import secrets
from pathlib import Path

ENV = Path(__file__).resolve().parents[1] / ".env"


def main() -> None:
    if ENV.exists():
        raise SystemExit(f"{ENV} already exists — delete it first to regenerate keys")
    ENV.write_text(
        "# Local development only. Generated by scripts/dev_env.py. Do not commit.\n"
        f"FTL_SIGNING_KEY={base64.b64encode(secrets.token_bytes(32)).decode()}\n"
        f"FTL_JWT_SECRET={secrets.token_urlsafe(48)}\n"
    )
    ENV.chmod(0o600)
    print(f"wrote {ENV}")


if __name__ == "__main__":
    main()
